WORK_FROM_HOME_ALT: 1
# WORK_FROM_HOME_ITERATIONS: 1
WORK_FROM_HOME_CHOOSER_FILTER: 1
WORK_FROM_HOME_COEFFICIENT_CONSTANT: 0.3
WORK_FROM_HOME_TARGET_PERCENT: 0.033
WORK_FROM_HOME_TARGET_PERCENT_TOLERANCE: 0.01
SPEC: work_from_home.csv
COEFFICIENTS: work_from_home_coefficients.csv
# LOGIT_TYPE: [NL, MNL]
# if LOGIT_TYPE == NL
# NESTS:
